// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7CC9W6Va1vD4-6NIHIFYcnPtIKnVNbLA',
    appId: '1:70025538383:web:5bc1c1f79ff5c204e8b33a',
    messagingSenderId: '70025538383',
    projectId: 'travelecommerce-7272f',
    authDomain: 'travelecommerce-7272f.firebaseapp.com',
    storageBucket: 'travelecommerce-7272f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIDmSUz2J1PPkOVEX-_POWI_gADep7I14',
    appId: '1:70025538383:android:e50ffe44373693e7e8b33a',
    messagingSenderId: '70025538383',
    projectId: 'travelecommerce-7272f',
    storageBucket: 'travelecommerce-7272f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAurWZnmOmfr5_kOYWtAAanEdmx2mqbD3c',
    appId: '1:70025538383:ios:2c9cbf850855dd66e8b33a',
    messagingSenderId: '70025538383',
    projectId: 'travelecommerce-7272f',
    storageBucket: 'travelecommerce-7272f.appspot.com',
    iosBundleId: 'com.example.test2ambw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAurWZnmOmfr5_kOYWtAAanEdmx2mqbD3c',
    appId: '1:70025538383:ios:2c9cbf850855dd66e8b33a',
    messagingSenderId: '70025538383',
    projectId: 'travelecommerce-7272f',
    storageBucket: 'travelecommerce-7272f.appspot.com',
    iosBundleId: 'com.example.test2ambw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7CC9W6Va1vD4-6NIHIFYcnPtIKnVNbLA',
    appId: '1:70025538383:web:890c40a355eaf8bfe8b33a',
    messagingSenderId: '70025538383',
    projectId: 'travelecommerce-7272f',
    authDomain: 'travelecommerce-7272f.firebaseapp.com',
    storageBucket: 'travelecommerce-7272f.appspot.com',
  );
}
